#!/usr/bin/env node

import { writeFile } from 'node:fs/promises';
import { domainToASCII } from 'node:url';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const SOURCE = 'https://publicsuffix.org/list/public_suffix_list.dat';
const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`PSL download failed: HTTP ${response.status}`);

const rules = (await response.text()).split(/\r?\n/)
  .map(line => line.replace(/\/\/.*$/, '').trim())
  .filter(Boolean)
  .map(rule => {
    const prefix = rule[0] === '!' ? '!' : rule.startsWith('*.') ? '*.' : '';
    const body = prefix === '!' ? rule.slice(1) : prefix === '*.' ? rule.slice(2) : rule;
    const ascii = domainToASCII(body.toLowerCase());
    if (!ascii) throw new Error(`Could not convert PSL rule: ${rule}`);
    return prefix + ascii;
  });

const generated = `/* AUTO-GENERATED by tools/update-psl.mjs.\n` +
  ` * Source: ${SOURCE}\n` +
  ` * The Public Suffix List is distributed under the Mozilla Public License 2.0.\n` +
  ` * Do not edit this file directly.\n */\n` +
  `(function (global) { 'use strict'; global.__PUBLIC_SUFFIX_RULES__ = ${JSON.stringify(rules)}; })(window);\n`;

await writeFile(join(repo, 'js/public-suffixes.js'), generated, 'utf8');
console.log(`Wrote ${rules.length} rules to js/public-suffixes.js`);
